<!DOCTYPE html>
<html>

<head>
    <title>Shipment Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .header {
            margin-bottom: 30px;
        }

        .matched {
            color: green;
            font-weight: bold;
        }

        .mismatched {
            color: red;
            font-weight: bold;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #777;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Shipment Inspection Report</h1>
        <p><strong>Shipment:</strong> {{ $vessel->vessel_name ?? 'N/A' }}</p>
        <p><strong>Arrival Date:</strong> {{ $vessel->arrival_date ? $vessel->arrival_date->format('Y-m-d') : 'N/A' }}</p>
        <p><strong>Generated:</strong> {{ now()->format('Y-m-d H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>SL No</th>
                <th>Tag No</th>
                <th>Species</th>
                <th>Original Specs (L/D/Vol)</th>
                <th>Verification</th>
                <th>Actual Specs (L/D/Vol)</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
            <tr>
                <td>{{ $log->serial_no }}</td>
                <td>{{ $log->tag_no }}</td>
                <td>{{ $log->species }}</td>
                <td>
                    {{ $log->length }}m / {{ $log->diameter }}cm <br>
                    <strong>{{ $log->vol_cbm }} CBM</strong>
                </td>
                <td>
                    @if($log->inspection && $log->inspection->is_match)
                    <span class="matched">MATCH</span>
                    @elseif($log->inspection)
                    <span class="mismatched">MISMATCH</span>
                    @else
                    PENDING
                    @endif
                </td>
                <td>
                    @if($log->inspection && !$log->inspection->is_match)
                    {{ $log->inspection->actual_length }}m / {{ $log->inspection->actual_diameter }}cm <br>
                    <strong>{{ $log->inspection->actual_vol_cbm }} CBM</strong>
                    @else
                    -
                    @endif
                </td>
                <td>
                    {{ $log->inspection->surveyor_remarks ?? '' }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by TimberLog Verify System
    </div>
</body>

</html>